spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradebot
    username: trader
    password: trader
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
server:
  port: 8080

app:
  ingest:
    defaultSymbol: BTCUSDT
    defaultInterval: 1m
